### ISSUE TITLE
Origins of coco_25 ckpt

### ISSUE THREAD

**Issue by gf0507033** [JunkyByte/easy_ViTPose#24]
Hi @JunkyByte, thx for great work!

In [original ViTPose repo](https://github.com/ViTAE-Transformer/ViTPose) there are no models with `coco_25`-like output. Can you provide more details on which dataset and hyperparameters have you trained your `coco_25` models?

**Comment by JunkyByte** [comment]
Hello! The coco-25 model was fine tuned from one of the original vitpose models by freezing the whole network but the last layer.
I refer to it as coco-25 because it is the standard coco + feet dataset https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/ (for a total of 25 key points)

There are not many details on the fine tuning process because it is currently not supported. We used to provide only the coco-25 model but then moved to support all original models and the coco-25 version became less important.

You can find more details in previous commits. To make the training compatible again the train.py must be changed in order to support the new formats of configs file used by the models.

This commit (previous to last large PR) should provide a working train.py setup

de43d54cad87404cf0ad4a7b5da6bacf4240248b

**Comment by JunkyByte** [comment]
I will add a reference about this in the readme because it is missing right now. Thanks for bringing it up

**Comment by gf0507033** [comment]
Thank you very much for the clarification!
